### ISSUE TITLE
Image of Candle for Light Candle

### ISSUE THREAD

**Issue by chinmayeebandal** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#104]
Create an image for Light the candle functionality. 

### Tasks Tests
- [x] A png image is created for lit candle.
- [x] A png image is created for unlit candle. 
- [x] This is a complete item
