### ISSUE TITLE
Day/Night Cycle - Backend

### ISSUE THREAD

**Issue by chinmayeebandal** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#106]
Implement the backend for Day and Night cycle and add Timer to keep track of the time. 

### Tasks Tests
- [x] Game state switches between night and day every X hours.
- [x] Can only interact with the ghost in night cycle.
- [x] Day and night states have a timer that shows time remaining until the player can interact with ghost.
- [x] Day state is skippable by toggling the sun button.
