### ISSUE TITLE
Day/Night Cycle toggle switch - Frontend

### ISSUE THREAD

**Issue by chinmayeebandal** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#107]
Toggle switch where Moon represents Night Cycle and Sun represents Day Cycle. Player can use the switch to toggle from Night Cycle to Day Cycle and vice-versa.

in cycle_timer.dart
### Tasks Tests
- [x] A switch button on the top left should exist
- [x] Image of moon on the top left
- [x] Clicking on the moon changes it to an image of sun
- [x] Clicking on sun changes it to moon
- [x] This is a complete item
