### ISSUE TITLE
The energy should increase/decrease based on certain conditions or player interactions with the ghost.

### ISSUE THREAD

**Issue by chinmayeebandal** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#108]
Implement the Energy progression system for the game based on user actions. 

### Tasks Tests
- [x] Energy starts at 100 (90 for testing purposes)
- [x] +5 after lighting the candle
- [x] -1 on choosing the wrong answer
- [x] Becomes 100 after entire Day cycle
- [x] +50 after toggling the Day cycle. Stays the same if they value goes beyond 100 after +50
