### ISSUE TITLE
If the energy bar is empty, the ghost should leave the player and return to the graveyard.

### ISSUE THREAD

**Issue by chinmayeebandal** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#113]
This task will integrate the energy bar to the back-end of the game. After this task is done, the energy bar will have the ability to reset the game when it is fully depleted.

### Tasks Tests
- [x] Ghost is released when energy becomes 0
- [x] Ghost remains if energy is not zero
- [x] When at the graveyard, if picked a different or same ghost energy should be either 5 for development or 100 for production.
