### ISSUE TITLE
Redesign Ghost Chat Screen

### ISSUE THREAD

**Issue by nbarrios1337** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#118]
Move around UI elements of the ghost interaction screen to be able to fit all of them within any screen size.

### Tasks Tests
- [ ] There is no render overflow on large-size phones
- [ ] There is no render overflow on medium-size phones
- [ ] There is no render overflow on small-size phones
