### ISSUE TITLE
App briefly displays the a placeholder game name on splash screen

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#12]
The splash

### Tasks Tests
- [x] The splash screen is the first thing display when opening the app
- [x] The splash screen displays placeholder text
- [x] The splash screen persists for 2 seconds
- [x] After 2 seconds, the splash screen goes away and the next page is rendered
