### ISSUE TITLE
Implement backend for "Donate energy" functionality

### ISSUE THREAD

**Issue by chinmayeebandal** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#122]
Implement the image switch, timer, score increase and energy decrease functionality for the Energy Donation feature. 

### Tasks Tests
- [x] Player energy decreases by 40.
- [x] Points increase by 75
- [x] Becomes available after 90 secs.
