### ISSUE TITLE
On first app launch, there's an explanation on Graveyard explaining what to do

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#137]
On the first app launch, there's an explanation on Graveyard explaining what to do

### Tasks Tests
- [x] A brief explanation about what it means to pick a ghost is present on a graveyard on the first launch
- [x] There is a progress indicator on the bottom which updates when the tutorial screen advances or goes back.
- [x] Clicking on the Skip Button will take the player to the last screen of the tutorial.
- [x] Clicking the arrow button will advance the tutorial to the next screen.
- [x] Left swipe will advance the tutorial screen and swiping right will take the player back to the previous tutorial screen.
- [x] Clicking on Done Button will end the tutorial and take the player back to the graveyard screen.
