### ISSUE TITLE
Tutorial walks you through your first interaction with your ghost

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#138]
The tutorial walks you through your first interaction with your ghost

### Tasks Tests
- [x] Shows where the cycle timer is and what it does.
- [x] Shows where the UI elements (energy well, health & and progress bar and candle) are and shows what they do 
- [x] Shows where the ghost's dialogue is
- [x] Shows where the player responses are and explains what players can do with it.
