### ISSUE TITLE
Synchronize all clocks/timers with larger state changes

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#145]
Synchronize all clocks/timers with larger state changes

### Tasks Tests
- [x] All timers should stop when the ghost is released
- [x] The candle & life timers should reset when day/night cycle changes
- [x] Timers should have timing lengths that are proportional to each other - e.g. life energy well timer is not longer than day/night cycle timer
