### ISSUE TITLE
Write simple question-response interactions for between levels

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#146]
Write simple question-response interactions for between all levels

### Tasks Tests
- [x] Create a set of ~10 simple single user question - ghost response interactions per level
- [x] They need not apply to the directly to the ghost's current, but can
- [x] Example: User: What time is it? Ghost: Yeah, let me just check my ghost watch, Points: 0
