### ISSUE TITLE
Add candle burning sound effect

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#154]
Add candle burning sound effect

### Tasks Tests
- [x] Locate a looped candle burning sound effect
- [x] Sound effect plays/loops while the candle is lit
- [x] Sound effect stops playing/looping when candle timer runs out
