### ISSUE TITLE
Create a Game model to contain many of our passed properties

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#156]
Create a Game model to contain many of our passed properties

### Tasks Tests
- [ ] Create a proper Game model
- [ ] Move the constants in the current Game model into a settings.dart constants library
- [ ] Move the Notifier, ghost released function, preferences, database, and Ghost model to be members/fields of the Game model
- [ ] Refactor to pass the Game model down where it's appropriate
