### ISSUE TITLE
When the Settings icon is pressed, a modal opens in the center of the screen

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#16]
When the Settings icon is pressed, a modal opens in the center of the screen

### Tasks Tests
- [x] Pressing the Settings button opens a modal
- [x] The modal is centered in the screen
- [x] The modal is blank and empty (for now)

**Comment by mferrera** [comment]
Closing this issue because I inadvertently re-created it in #18. It is ~~not~~ complete.
