### ISSUE TITLE
When the Settings icon is pressed, a modal opens in the center of the screen

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#18]
When the Settings icon is pressed, a modal opens in the center of the screen

### Tasks Tests
- [x] The Settings icon can be pressed
- [x] Upon pressing the settings icon, a modal opens in the center of the screen
- [x] The modal is on a layer above the main game screen
- [x] The modal does not cover the entirety of the screen, and the game remains visible in the non-covered parts behind it

**Comment by mferrera** [comment]
Completed.
