### ISSUE TITLE
Write tests for the ghost main screen

### ISSUE THREAD

**Issue by anarghya-das** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#29]
These tests should be written using the flutter widget test and should verify if everything is displayed properly on the screen. 

### Tasks Tests
- [ ] The image of the ghost is visible. 
- [ ] The image of the ghost is positioned above the four buttons. 
- [ ] The four buttons are aligned properly. 
- [ ] Both the components (Ghost picture and text) should be positioned at the center of the screen.
