### ISSUE TITLE
A "Reset Database" button is present that sets all states and settings back to those of a fresh game

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#67]
A "Reset Database" button is present that sets all states and settings back to those of a fresh game

### Tasks Tests
- [x] A "!! Reset Database !!" button is present in the Dev Settings menu
- [x] Pressing this button deletes the database and re-seeds a fresh one
- [x] Pressing this button sets your state back to the graveyard
