### ISSUE TITLE
Implement the Progression system - System

### ISSUE THREAD

**Issue by chinmayeebandal** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#71]
Implementing the scheme for the progression system based on the score, progress and level to help the game move forward. 

### Tasks Tests
- [x] Scheme for score
- [x] Scheme for progress based on level
- [x] Scheme for level based on progress
- [x] Scheme for Night cycles for each level
- [x] Scheme for points for options the player chooses.
