### ISSUE TITLE
Create the progress bar for the progression system

### ISSUE THREAD

**Issue by nbarrios1337** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#72]
Add a ui element showing how are along the user needs to interact until the next story event.

### Tasks Tests
- [x] The progress meter should be present in the ghost interaction screen
- [x] The bar should increase in size upon a a positive interaction
- [x] The bar should reset after a story milestone.
