### ISSUE TITLE
Create the first ghost story

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#73]
Create the first ghost story.
It needs to be broken down into 10 or so tiers of progress.
This story includes all initial messages from the ghost as well as all possible responses from the user to those prompts.

### Tasks Tests
- [x] Write a general story for the first ghost (clock maker)
- [x] Delineate the story into 10 tiers of progress
- [x] Fit the written story into these 10 tiers
