### ISSUE TITLE
Refactor `ghost_main`, screens, clean-up code & images

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#75]
ghost_main is messy and our code could and should be a bit more organized.
Refactoring these now will make our lives easier when we add more advanced interactions.

### Tasks Tests
- [x] Split widgets out of `ghost_main.dart` and `graveyard_main.dart` into individual widget files in `widgets/`
- [x] Make a `screens/` directory, move the above two files into it along with `splash_screen.dart`
- [x] Fix whatever these file moves break
- [x] Move the graveyard background widget image out of ghost/graveyard screens and higher so it's only rendered once (perhaps in `app.dart`
- [x] Fix ghost/image asset sizes. Clean up the empty canvas around them
