### ISSUE TITLE
Write a script to convert Twine .json files into sql statements

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#76]
To add story and user/ghost responses to the game, we need to convert the Twine json files into sql statements. This is specific to story events.

### Tasks Tests
- [x] The script takes three parameters: the ghost #, the "prompt" table, and the "response" table
- [x] The prompt table corresponds to each passage object in the passages array
- [x] Each passage item must have the responses stripped out of its text (the stuff in [[ ]])
- [x] Each passage item is its own row
- [x] Each passage item row links to every object in the "items" array contained within in its object
- [x] Each "link" object is a row in the response table, and each of these links back to another item in the "prompt" table
