### ISSUE TITLE
Pressing an interaction button increases the user's score in the database - Backend

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#77]
Every interaction should add to the user's score in the database
The added score can range from 0-5 points. 0 for "bad" interactions, and 5 for "good" interactions
5 points should generally be reserved for "good" interactions on story events at every level up

### Tasks Tests
- [x] Interaction buttons have an associated score
- [x] The associated score is stored in interaction data (temporary: use & modify Lisander's dummy data)
- [x] Pressing a button updates the user's score in the database
