### ISSUE TITLE
Create Ghost 1's story in Twine and export it as .json

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#79]
The story created in #73 should be put together in Twine and exported as json

### Tasks Tests
- [x] Create every ghost level-up interaction in a separate Twine storyboard for ghost 1
- [x] Export it as .json and add to the story directory
- [x] The created twine story should be interactive and the player should be able to play through it.
