### ISSUE TITLE
A candle is present on the screen during the night and can be lit

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#95]
A candle is present on the screen during the night and can be lit

### Tasks Tests
- [x] A Candle icon button is present on the UI.
- [x] The candle button can only be pressed during the night cycle
- [x] If the candle button is pressed during the night cycle, it's icon changes to a lit candle
- [x] When the candle is lit, it cannot be pressed
