### ISSUE TITLE
While the candle is lit, the player cannot interact with the ghost

### ISSUE THREAD

**Issue by mferrera** [cse442-spring-2020-offering/cse442-semester-project-bugs-are-features#99]
While the candle is lit, the player cannot interact with the ghost

### Tasks Tests
- [x] A lit candle prevents communication interactions with the ghost
- [x] A lit candle prevents any and all other future interactions with the ghost (e.g. life force giving)
- [x] The above two things are accomplished by setting a state
